FROM node:20.9.0-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

COPY client/package.json client/pnpm-lock.yaml* ./

RUN pnpm install

COPY client/ .

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host"]
